<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS) ; ?>jquery.validate.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
    jQuery("#empty_toner_form").validate({
        // Specify the validation rules
        rules: {
            companyname: "required",
            contactname: "required",
            phone: {
                required: true,
                number: true,
                minlength: 10,
                maxlength:15
            },
            email: {
                required: true,
                email: true
            },
            comment:"required"
        },
        // Specify the validation error messages
        messages: {
            companyname: "Please enter your company name",
            contactname: "Please enter your name",
            phone: {
                required: "Please provide a Phone Number",
                number:"Please enter numbers only",
                minlength: "Your phone number must be at least 10 digit long",
                maxlength: "Your phone number must be at most 15 digit long"

            },
            email: "Please enter a valid email address",
            comment: "Please Enter Comments"
        },
        submitHandler: function(form) {
            //return false;
            form.submit();
        }
    });
  });
</script>

<?php if ($messages = $this->getNoteMessages()):?>
    <p class="note-msg">
        <?php foreach ($messages as $message):?>
            <?php echo $message?><br />
        <?php endforeach;?>
    </p>
<?php endif; ?>
   
<div class="page-title">
    <h1>Recycle Empty Toner</h1>
</div>
<div class="std"><h3>Fill all the information for recycle empty toners</h3>
    <form id="empty_toner_form" name="empty_toner_form" action="<?php echo $this->getUrl('recycle-empty-toner/') ?>index/sendemail" role="form" method="POST">
        <div class="form-group">
            <label for="companyname">Company Name *</label>
            <input type="text" class="form-control" id="companyname" name="companyname"  placeholder="Company Name" value="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ echo Mage::getSingleton('customer/session')->getCustomer()->getPrimaryBillingAddress()->getCompany() ; }  ?>" />
        </div>
        <div class="form-group">
            <label for="name">Contact Name *</label>
            <input type="text" class="form-control" id="contactname" name="contactname" value="<?php if(isset($name)&&!empty($name)){ echo $name ; }?>" placeholder="Contact Name" />
        </div>
        <div class="form-group">
            <label for="phone">Phone # *</label>
            <input type="text" class="form-control" id="phone" name="phone"  placeholder="Enter phone" value="<?php if(Mage::getSingleton('customer/session')->isLoggedIn()){ echo Mage::getSingleton('customer/session')->getCustomer()->getPrimaryBillingAddress()->getTelephone() ;  }  ?>" />
        </div>
        <div class="form-group">
            <label for="E-Mail">E-Mail Address *</label>
            <input type="text" class="form-control" id="email" name="email" value="<?php if(isset($email)&&!empty($email)){ echo $email ; }?>" placeholder="Enter E-Mail" />
        </div>
        <div class="form-group">
            <label for="comment"> Please attach or tape as many boxes together of each cartridge as possible. We either need the total weight of each box OR how many of each type of cartridge is in each box. This is the only way we are able to calculate the weight for the UPS Prepaid Return Label.</label>
            <textarea class="form-control" rows="5" id="comment" name="comment"></textarea>
        </div>
        <button type="submit" class="btn btn-default">Send Request</button>
    </form>
</div>