<link href="<?php echo $this->getSkinUrl("css/inktoner.css"); ?>" rel="stylesheet" type="text/css" />
<script type="text/javascript">
    function getCategories(id){
        url = '<?php echo Mage::getUrl('catalog/inktoner/getCategories');?>?id='+id;
    	jQuery.ajax({
			url: url,
			success: function(data){
			   jQuery("#categories").html(data);
			},
			error: function(){
				
			}
        });
    }

    function getModels(id){
        url = '<?php echo Mage::getUrl('catalog/inktoner/getCategoryModels');?>?id='+id;
    	jQuery.ajax({
			url: url,
			success: function(data){
			   jQuery("#models").html(data);
			},
			error: function(){
				
			}
        });
    }

    function getKeywords(){
    	jQuery(document).ready(function($) {
	    	type = (jQuery("#search_type1").prop("checked")) ? 'cartridge' : 'printer';
	    	console.log(type);
	    	
	    	if(type == 'cartridge'){
	       		jQuery("#keyword").ssTypeAhead({serviceURL:"https://ta.ussco.com/smartchoice/smart-suggestions.jsonp",minlength:1,keywordInterface:"ImageSupplies"});
	    	}
	    	else{
	       		jQuery("#keyword").ssTypeAhead({serviceURL:"https://ta.ussco.com/smartchoice/smart-suggestions.jsonp",minlength:1,keywordInterface:"SuppliesFinderModel"});
	    	}
    	});
    	
    	/*url = '< ?php echo Mage::getUrl('catalog/inktoner/getKeywords');? >?type='+type;
    	jQuery("#keyword").autocomplete({
        	source : url
        });*/
    }
</script>
<div class="inktoner-main">
  <div class="header_back">Your Ink and Toner Finder </div>
  <div class="inktoner_bg">
    <div class="leftpart">
       <form method="get" action="<?php echo $this->getSearchUrl()?>">	
	    	<h3>Search for Printer</h3>
            <div class="space">
            	<select name="brand" id="brand" onchange="getCategories(this.value)" class="form-control">
            		<option value="">Select One</option>
            		<?php foreach($this->getBrands() as $brand):?>
            			<option value="<?php echo $brand['id']?>"><?php echo $brand['supplier_name']?></option>
            		<?php endforeach;?>
            	</select>
            </div>
            
            <div class="space" id="categories">
            	<select name="category" id="category" disabled="disabled" class="form-control">
            		<option>Select One</option>
            	</select>
            </div>
            
            <div class="space" id="models">
            	<select name="model" id="model" disabled="disabled" class="form-control">
            		<option>Select One</option>
            	</select>
            </div>
            <button type="submit" class="btn btn-success" style=" background:#60a810;">Search</button>
        </form>
    </div>

    <div class="midpart"></div>

    <div class="rightpart">
       <form method="get" action="<?php echo $this->getSearchUrl()?>">
	      <h3>Search by cartridge or printer</h3>
	      <div class="space">
				<div class="radiobtn radio" style="padding-left:0;">
				   <input name="search_type" type="radio" checked="checked" value="cartridge" id="search_type1"  />
				</div>
				
				<div class="f_left"> Cartridge</div>
			
				<div class="radiobtn radio" style="padding-left:10px;">
				    <input name="search_type" type="radio" value="printer" id="search_type2"  />
				</div>
				<div class="f_left"> Printer</div>
	      		<div class="clearBoth"> </div>   
	       </div>
	      
	       <div class="space" style="position:relative;">
		  	   <input name="keyword" type="text" id="keyword" placeholder="keyword" onkeypress="getKeywords()" onkeyup="getKeywords()" class="form-control inputs" />
		   </div>
            
           <div>   
            	<button type="submit" class="btn btn-success" style=" background:#60a810;">Go</button>	
           </div>
		   <div class="clearBoth"></div>
	      
	      <div class="space"><a href="#allbrands">See all Brands</a></div>
	   </form>
    </div>
    <div class="clearBoth"> </div>
  </div>
  <div class="clearBoth"> </div>
</div>

<br />

<?php $supplies_models = $this->getSuppliesModels();?>

<div class="listing" id="listing">
  <?php if(sizeof($supplies_models) > 0):?>
	<div style="border:1px solid #e5e5e5;">
		<?php foreach($supplies_models as $supplies_model):?>
			  <?php if(sizeof($supplies_model['Models']) > 0):?>
			 		<h4 style="background:#D0DCF5;padding:5px;"><?php echo $supplies_model['CategoryName'];?></h4>
			 		<br clear="all" />
			 
			 		<ul class="productlist">
				 		<?php foreach($supplies_model['Models'] as $model):?>
				 				<?php $url_parameters = "fst1=SuppliesFinderBrand&fid11=".$_REQUEST['m']."&fst2=SuppliesFinderDeviceType&fid21=".$supplies_model['Value']."&fst3=SuppliesFinderModel&fid31=".$model['Value'];?>
				 	
								<li><a href="<?php echo Mage::getUrl("catalogsearch/smart/")."?q=printers&".$url_parameters;?>"><?php echo $model['ModelName'];?></a></li>
						<?php endforeach;?>		
					</ul>
					<div style="clear:both"><br clear="all" /></div>
			 <?php endif;?>	
		<?php endforeach;?>	
	</div>		
  <?php endif;?>		 		
  <div style="clear:both"></div>
</div>